Repository Okty-io/okty-server, pull requests merged in 2019-06, with the labels that each got.

#99 Update to Symfony 4.3
  composer.json
  composer.lock
  symfony.lock
Labels: dependencies

#100 Add registry search endpoint
  composer.json
  composer.lock
  src/Controller/Api/Registry/Search.php
  symfony.lock
Labels: feature

#106 Import learning data
  src/Controller/Api/Learning/Chapter/Index.php
  src/Controller/Api/Learning/Deploy.php
  src/DataFixtures/ChaptersFixtures.php
  src/Entity/Learning/Action.php
  src/Entity/Learning/Chapter.php
  src/Entity/Learning/Lesson.php
  src/Repository/Learning/ChapterRepository.php
  src/Repository/Learning/ChapterRepositoryInterface.php
  src/Repository/Learning/LessonRepository.php
  src/Repository/Learning/LessonRepositoryInterface.php
  src/Service/Github.php
  src/Service/Learning/Import.php
  src/ValueObject/Learning/Github/Action.php
  src/ValueObject/Learning/Github/Chapter.php
  src/ValueObject/Learning/Github/Lesson.php
  src/ValueObject/Learning/Github/Step.php
Labels: feature

#108 Fix migrations
  config/packages/doctrine.yaml
  src/Migrations/Version20190218211250.php
  src/Migrations/Version20190219232615.php
  src/Migrations/Version20190612180645.php
  src/Migrations/Version20190612190952.php
Labels: bug

#139 Add builder auth
  composer.lock
  config/services.yaml
  docker-compose.yml
  src/Command/LearningImportCommand.php
  src/Controller/Api/Learning/Deploy.php
  src/EventListener/JWTCreatedListener.php
  src/Repository/UserRepositoryInterface.php
  src/Service/Learning/Import.php
Labels: Deploy

#141 Add contributor data in pull request
  src/Controller/Api/Builder/Submit.php
  src/Migrations/Version20190629173542.php
Labels: Deploy

#143 Fix ID Regex
  src/ValueObject/Service/Id.php
Labels: Deploy
